### ISSUE TITLE
ADO_NET nummering

### ISSUE THREAD

**Issue by SuperMcBrent** [lucvervoort/Pdf#1]
ADO_NET.pdf page1 18.1.2 -> 1.1.2
ADO_NET.pdf page2 18.1.2.1 -> 1.1.2.1

**Comment by lucvervoort** [comment]
Hoi Brent,,

tnx! Corrected 😉

L
________________________________
Van: Brent <notifications@github.com>
Verzonden: woensdag 4 maart 2020 3:03
Aan: lucvervoort/Pdf <Pdf@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [lucvervoort/Pdf] ADO_NET nummering (#1)


ADO_NET page1 18.1.2 -> 1.1.2
ADO_NET page2 18.1.2.1 -> 1.1.2.1
